/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import org.example.domain.Estacionamiento;
import org.example.repository.EstacionamientoRepository;
import utils.Utils;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author クリス
 */
public class EstacionamientoGUI extends javax.swing.JFrame {
    private Boolean isCreate;
    /**
     * Creates new form EstacionamientoGUI
     */
    public EstacionamientoGUI(Boolean isCreate) {
        this.isCreate = isCreate;
        initComponents();
        load();
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow != -1) { // Verificar que haya una fila seleccionada
                    // Llenar los campos de entrada con los valores de la fila seleccionada
                    txtEstacionamientoId.setText(jTable1.getValueAt(selectedRow, 0).toString());
                    txtPlaca.setText(jTable1.getValueAt(selectedRow, 1).toString());
                    jRadioButton1.setSelected((Boolean) jTable1.getValueAt(selectedRow, 3));

                    String dateString = jTable1.getValueAt(selectedRow, 2).toString();

                    var originalFormat = new SimpleDateFormat("yyyy-MM-dd");
                    var desiredFormat = new SimpleDateFormat("dd/MM/yyyy");

                    try {
                        var date = originalFormat.parse(dateString);
                        String formattedDate = desiredFormat.format(date);
                        txtFechaRegistro.setText(formattedDate);
                    } catch (ParseException error) {
                        error.printStackTrace();
                    }
                }
            }
        });
        if (this.isCreate) {
            jButton1.setText("Guardar");
        } else {
            jButton1.setText("Actualizar");
        }
    }

    public EstacionamientoGUI() {
        this.isCreate = true;
        initComponents();
        jButton1.setText("Guardar");
        load();
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow != -1) { // Verificar que haya una fila seleccionada
                    // Llenar los campos de entrada con los valores de la fila seleccionada
                    txtEstacionamientoId.setText(jTable1.getValueAt(selectedRow, 0).toString());
                    txtPlaca.setText(jTable1.getValueAt(selectedRow, 1).toString());
                    jRadioButton1.setSelected((Boolean) jTable1.getValueAt(selectedRow, 3));

                    String dateString = jTable1.getValueAt(selectedRow, 2).toString();

                    var originalFormat = new SimpleDateFormat("yyyy-MM-dd");
                    var desiredFormat = new SimpleDateFormat("dd/MM/yyyy");

                    try {
                        var date = originalFormat.parse(dateString);
                        String formattedDate = desiredFormat.format(date);
                        txtFechaRegistro.setText(formattedDate);
                    } catch (ParseException error) {
                        error.printStackTrace();
                    }
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtEstacionamientoId = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtFechaRegistro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Estacionamiento ID:");

        jLabel2.setText("Placa:");

        jLabel3.setText("Fecha Registro:");

        jRadioButton1.setText("Disponible");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtEstacionamientoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstacionamientoIdActionPerformed(evt);
            }
        });

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        txtFechaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaRegistroActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEstacionamientoId, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtEstacionamientoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButton1)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstacionamientoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstacionamientoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstacionamientoIdActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtFechaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaRegistroActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        var estacionamientoId = txtEstacionamientoId.getText();
        var placa = txtPlaca.getText();
        var fechaRegistro = txtFechaRegistro.getText();
        var disponible = jRadioButton1.isSelected();

        if (estacionamientoId.isEmpty() || placa.isEmpty() || fechaRegistro.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos los campos son requeridos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        var fecha = Utils.convertirStringADate(fechaRegistro);

        if (fecha == null) {
            JOptionPane.showMessageDialog(null, "La fecha no tiene el formato correcto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        var estacionamiento = new Estacionamiento();
        estacionamiento.setEstacionamientoId(Integer.parseInt(estacionamientoId));
        estacionamiento.setPlaca(placa);
        estacionamiento.setFechaRegistro(fecha);
        estacionamiento.setDisponible(disponible);

        try {
            var estacionamientoRepository = new EstacionamientoRepository();

            if (this.isCreate) {
                estacionamientoRepository.save(estacionamiento);
            } else {
                estacionamientoRepository.update(estacionamiento);
            }

            load();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Ocurrio un error al guardar el estacionamiento", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        var estacionamientoId = txtEstacionamientoId.getText();
        if (estacionamientoId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo de estacionamiento ID es requerido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            var estacionamiento = new Estacionamiento();
            estacionamiento.setEstacionamientoId(Integer.parseInt(estacionamientoId));
            var estacionamientoRepository = new EstacionamientoRepository();
            estacionamientoRepository.delete(estacionamiento);
            JOptionPane.showMessageDialog(null, "Estacionamiento eliminado correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            load();
            clean();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Ocurrio un error al eliminar el estacionamiento", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void clean() {
        txtEstacionamientoId.setText("");
        txtPlaca.setText("");
        txtFechaRegistro.setText("");
        jRadioButton1.setSelected(false);
    }
    
    private void load() {
        try {
            var estacionamientoRepository = new EstacionamientoRepository();
            var estacionamientos = estacionamientoRepository.readAll();
            var columnNames = new String[]{"Estacionamiento ID", "Placa", "Fecha Registro", "Disponible"};
            var model = new DefaultTableModel(columnNames, 0);

            for (var estacionamiento : estacionamientos) {
                var row = new Object[]{estacionamiento.getEstacionamientoId(), estacionamiento.getPlaca(), estacionamiento.getFechaRegistro(), estacionamiento.getDisponible()};
                model.addRow(row);
            }
            jTable1.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Ocurrio un error al cargar los estacionamientos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEstacionamientoId;
    private javax.swing.JTextField txtFechaRegistro;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
