/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ItemEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author casa
 */
public class MenuGUI extends javax.swing.JFrame {
    private PersonaGUI personaGUI;
    private VehiculoGUI vehiculoGUI;
    private EstacionamientoGUI estacionamientoGUI;
    /**
     * Creates new form Menu
     */
    public MenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        IngresarPersona = new javax.swing.JMenuItem();
        ModificarPersona = new javax.swing.JMenuItem();
        IngresarVehiculo = new javax.swing.JMenuItem();
        ModificarVehiculo = new javax.swing.JMenuItem();
        IngresarEstacionamiento = new javax.swing.JMenuItem();
        ModificarEstacionamiento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("jMenu3");
        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        IngresarPersona.setText("Ingresar Persona");
        IngresarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarPersonaActionPerformed(evt);
            }
        });
        jMenu2.add(IngresarPersona);

        ModificarPersona.setText("Modificar Persona");
        ModificarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarPersonaActionPerformed(evt);
            }
        });
        jMenu2.add(ModificarPersona);

        IngresarVehiculo.setText("Ingresar Vehiculo");
        IngresarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarVehiculoActionPerformed(evt);
            }
        });
        jMenu2.add(IngresarVehiculo);

        ModificarVehiculo.setText("Modificar Vehiculo");
        ModificarVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarVehiculoMouseClicked(evt);
            }
        });
        ModificarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarVehiculoActionPerformed(evt);
            }
        });
        jMenu2.add(ModificarVehiculo);

        IngresarEstacionamiento.setText("Ingresar Estacionamiento");
        IngresarEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarEstacionamientoActionPerformed(evt);
            }
        });
        jMenu2.add(IngresarEstacionamiento);

        ModificarEstacionamiento.setText("Modificar Estacionamiento");
        ModificarEstacionamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarEstacionamientoMouseClicked(evt);
            }
        });
        ModificarEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarEstacionamientoActionPerformed(evt);
            }
        });
        jMenu2.add(ModificarEstacionamiento);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarPersonaActionPerformed
        if (personaGUI == null || !personaGUI.isVisible()) {
            personaGUI = new PersonaGUI(true);
            personaGUI.setVisible(true);
            personaGUI.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            personaGUI.toFront();
            personaGUI.requestFocus();
        }
    }//GEN-LAST:event_IngresarPersonaActionPerformed

    private void ModificarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPersonaActionPerformed
        if (personaGUI == null || !personaGUI.isVisible()) {
            personaGUI = new PersonaGUI(false);
            personaGUI.setVisible(true);
            personaGUI.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            personaGUI.toFront();
            personaGUI.requestFocus();
        }
    }//GEN-LAST:event_ModificarPersonaActionPerformed

    private void IngresarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarVehiculoActionPerformed
        if (vehiculoGUI == null || !vehiculoGUI.isVisible()) {
            vehiculoGUI = new VehiculoGUI(true);
            vehiculoGUI.setVisible(true);
            vehiculoGUI.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            vehiculoGUI.toFront();
            vehiculoGUI.requestFocus();
        }
    }//GEN-LAST:event_IngresarVehiculoActionPerformed

    private void ModificarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarVehiculoActionPerformed
        if (vehiculoGUI == null || !vehiculoGUI.isVisible()) {
            vehiculoGUI = new VehiculoGUI(false);
            vehiculoGUI.setVisible(true);
            vehiculoGUI.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    System.out.println("openm");
        } else {
            vehiculoGUI.toFront();
            vehiculoGUI.requestFocus();
                    System.out.println("openm2");
        }
    }//GEN-LAST:event_ModificarVehiculoActionPerformed

    private void IngresarEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarEstacionamientoActionPerformed
        if (estacionamientoGUI == null || !estacionamientoGUI.isVisible()) {
            estacionamientoGUI = new EstacionamientoGUI(true);
            estacionamientoGUI.setVisible(true);
            estacionamientoGUI.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            estacionamientoGUI.toFront();
            estacionamientoGUI.requestFocus();
        }
    }//GEN-LAST:event_IngresarEstacionamientoActionPerformed

    private void ModificarEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarEstacionamientoActionPerformed
        if (estacionamientoGUI == null || !estacionamientoGUI.isVisible()) {
            estacionamientoGUI = new EstacionamientoGUI(false);
            estacionamientoGUI.setVisible(true);
            estacionamientoGUI.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            estacionamientoGUI.toFront();
            estacionamientoGUI.requestFocus();
        }
    }//GEN-LAST:event_ModificarEstacionamientoActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

    }//GEN-LAST:event_jMenu2MouseClicked

    private void ModificarVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarVehiculoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ModificarVehiculoMouseClicked

    private void ModificarEstacionamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarEstacionamientoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarEstacionamientoMouseClicked

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem IngresarEstacionamiento;
    private javax.swing.JMenuItem IngresarPersona;
    private javax.swing.JMenuItem IngresarVehiculo;
    private javax.swing.JMenuItem ModificarEstacionamiento;
    private javax.swing.JMenuItem ModificarPersona;
    private javax.swing.JMenuItem ModificarVehiculo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
